name = "bbt"
description = "Black box test runner"
version = "0.0.4"

authors = ["Lionel Draghi"]
maintainers = ["Lionel Draghi <lionel.draghi@free.fr>"]
maintainers-logins = ["LionelDraghi"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["gherkin", "test", "markdown", "tdd", "black-box"]

executables = ["bbt"]

[configuration]
output_dir = "src/Alire_config"
generate_C = false

[[depends-on]]
# markdown = "^24.0.0"



[origin]
commit = "4a1ed2bd6c9c1b50485d26cc9c5e7b8ccc546694"
url = "git+https://github.com/LionelDraghi/bbt.git"

